### PR TITLE
Admin tools

### PR DESCRIPTION
**Pull request by Kenny2github**
- Change previous URL parameter-based session system for registration endpoints to cookie-based system
- Add ratelimits and admin API endpoints to set them
- Add bans and admin API endpoints to use them
- Add an admin API endpoint to get client info for better context
- Change documented API root because SSL works now! (Previous root still works for backwards compatibility but it is not recommended because you'll be sending your token in the clear.)

### CODE REVIEW

**Review by Semisol — CHANGES_REQUESTED** [review]
Failing checks.

**Comment by Semisol** [comment]
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/hostedtoolcache/Python/3.7.8/x64/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 15, in <module>
    config['admins'],
KeyError: 'admins'
EEEEEEEEEEE

**Comment by Semisol** [comment]
u forgot to update the config?

**Comment by Kenny2github** [comment]
@Semisol *you* forgot to update the config! That traceback disappeared once I included `"admins": ["Kenny2scratch"]` on my local instance's config.

**Comment by Semisol** [comment]
like

**Comment by Semisol** [comment]
the test failed on that

**Comment by Kenny2github** [comment]
> Failing checks.

@Semisol I've opened #57 for that - currently GH doesn't know how to run our tests.

**Comment by Semisol** [comment]
Okay

**Comment by Kenny2github** [comment]
> the test failed on that

No, the test failed on "Connection refused" because the debug server wasn't running to accept requests.

**Comment by Semisol** [comment]
Let me show you

**Comment by Semisol** [comment]
the tests kind of broke but
the connection refused is fixed now
which was caused the server failing to access $.admins configuration property
on run

**Comment by Semisol** [comment]
and crashing

**Comment by Semisol** [comment]
seems right

**Comment by Kenny2github** [comment]
I'm just going to merge this - @Semisol can review the pull to master

**Pull request merged**
