### PR TITLE
GitHub updates, small bugfix, better error logging

### PR DESCRIPTION
**Pull request by Kenny2github**
* Add code security analysis
* Add Discord invite
* Fix small bug: undefined variable that was somehow not caught before
* Make Discord error logs log headers too so that we can debug #73

### CODE REVIEW

**Comment by Semisol** [comment]
will review the pull in a sec.

**Comment by Semisol** [comment]
> * Add code quality analysis
you meant adding code security analysis, i will check in a second

**Comment by Kenny2github** [comment]
remember merging to master should be a rebase merge

**Comment by Semisol** [comment]
ok

**Review by Semisol — APPROVED** [review]

**Comment by Semisol** [comment]
rebased

**Comment by Kenny2github** [comment]
nice, now we can start pinning down the issue #73

**Comment by Semisol** [comment]
ok

**Pull request merged**
