### PR TITLE
Tests! Also fixed bugs found with them.

### LINKED ISSUE #20: Create tests for API endpoints
- [x] `PUT /verify/{username}`
  - [x] 401 without authorization
  - 404 for 404ing username (test manually)
  - [x] 400 for blank or >20c or <3c username
  - [x] 200 with authorization on valid name
  - [x] Returns Verification object
  - [x] Returns same code for repeated start
- [x] `POST /verify/{username}`
  - [x] 4xx same as PUT
  - [x] 204 for successful verification
  - [x] 403 for unsuccessful verification
- [x] `DELETE /verify/{username}`
  - [x] 4xx same as PUT
  - [x] 204 for successful deletion
- [x] `POST /users/{username}/login`
  - [x] 4xx same as `PUT /verify/{username}` minus the 401
  - [x] 200 returns Verification object
- [x] `POST /users/{username}/finish-login`
  - [x] 4xx same as `POST /verify/{username}` but 403 becomes 401, replacing original
  - [x] 200 returns Session object
- [x] `GET /session/{session}`
  - [x] 401 for invalid session ID
  - [x] 404 if no client is registered with this user
  - [x] 200 returns User object
- [x] `PUT /session/{session}`
  - [x] 401 for invalid session ID
  - [x] 409 if client is already registered
  - [x] 200 returns User object
- [x] `PATCH /session/{session}`
  - [x] 401 for invalid session ID
  - [x] 200 returns User object
  - New token is not the same as previous (can't really be tested)
- [x] `DELETE /session/{session}`
  - [x] 401 for invalid session ID
  - [x] 204 on success
- [x] `GET /usage`
  - [x] 403 on limit > 500
  - [x] 200 returns list of Log objects
- [x] `GET /usage/{log id}`
  - [x] 404 for nonexistent log ID
  - [x] 200 returns single Log object

### PR DESCRIPTION
**Pull request by Kenny2github**
Resolves #20

```
backend/__main__.py:
+ --debug runs server in debug mode, necessary
  for testing

backend/server.py:
+ POST /debug/{value} to set debug mode
  * this only works if server was also run
    in debug mode (--debug)
  * value is two bits:
    * debug_pass - POST /verify will succeed
    * debug - bypass most auth stuff to test
      functionality
  * 500s are printed to console instead of
    logged to Discord
* Fix: username if missing from match info is
  the empty string
* Fix: username regex matched "Impossible"
  in "Impossible Username", now regex uses ^$

backend/db.py:
* Handle debug mode
+ DELETE FROM sessions and usage where expired

backend/responses.py:
* Responses now have custom __instancecheck__
  which checks whether the structure of a dict
  matches the attributes and types
* Changed attr = type to attr: type

+tests.py:
* Must have backend running --debug
+ TestApi
  + .test_start PUT /verify/{}
  + .test_end POST /verify/{}
  + .test_cancel DELETE /verify/{}
+ TestLogin
  + .test_login POST /users/{}/login
  + .test_finish_login
    POST /users/{}/finish-login
  + .test_get_client GET /session/{}
  + .test_put_client PUT /session/{}
  + .test_patch_client PATCH /session/{}
  + .test_delete_client DELETE /session/{}
+ TestLogging
  + .test_logs GET /usage
  + .test_log GET /usage/{}

requirements.txt:
* tests.py needs requests
```

### CODE REVIEW

**Comment by smileycreations15** [comment]
lemme test the tests :P

**Comment by Kenny2github** [comment]
THINGS YOU NEED TO KNOW

before running `py tests.py`, you need to `py backend --debug` for it to actually have something to test

**Comment by smileycreations15** [comment]
😮 ok

**Comment by smileycreations15** [comment]
why that failed 😛

**Comment by smileycreations15** [comment]
@Kenny2github why it is only your username take that from the config :P

**Comment by Kenny2github** [comment]
@smileycreations15 if it was taken from config you could fail the test by specifying an invalid username. Mine is guaranteed to be valid.

**Comment by smileycreations15** [comment]
But then how would I test :P

**Comment by smileycreations15** [comment]
add it as an arg or something

**Pull request merged**
